const TYPES = {
    FETCH_DATA_CATEGORIES_SUCCESS: "FETCH_DATA_CATEGORIES_SUCCESS",
    FETCH_DATA_CATEGORIES_LOADING: "FETCH_DATA_CATEGORIES_LOADING",
    FETCH_DATA_CATEGORIES_ERROR: "FETCH_DATA_CATEGORIES_ERROR"
};
export { TYPES };
