const TYPES = {
  FETCH_DATA_CATEGORIES_SUCCESS: "FETCH_DATA_CATEGORIES_SUCCESS",
  FETCH_DATA_CATEGORIES_LOADING: "FETCH_DATA_CATEGORIES_LOADING",
  FETCH_DATA_CATEGORIES_ERROR: "FETCH_DATA_CATEGORIES_ERROR",
  FETCH_DATA_PRODUCTS_SUCCESS: "FETCH_DATA_PRODUCTS_SUCCESS",
  FETCH_DATA_PRODUCTS_LOADING: "FETCH_DATA_PRODUCTS_LOADING",
  FETCH_DATA_PRODUCTS_ERROR: "FETCH_DATA_PRODUCTS_ERROR",
  SEARCH_DATA_PRODUCTS_SUCCESS: "SEARCH_DATA_PRODUCTS_SUCCESS",
  SEARCH_DATA_PRODUCTS_LOADING: "SEARCH_DATA_PRODUCTS_LOADING",
  SEARCH_DATA_PRODUCTS_ERROR: "SEARCH_DATA_PRODUCTS_ERROR",
};
export { TYPES };
