const TYPES = {
  FETCH_DETAIL_PRODUCT_SUCCESS: "FETCH_DETAIL_PRODUCT_SUCCESS",
  FETCH_DETAIL_PRODUCT_LOADING: "FETCH_DETAIL_PRODUCT_LOADING",
  FETCH_DETAIL_PRODUCT_ERROR: "FETCH_DETAIL_PRODUCT_ERROR",
};
export { TYPES };
