const TYPES = {
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_LOADING: "GET_CART_LOADING",
  GET_CART_ERROR: "GET_CART_ERROR",
  UPDATE_CART_LOADING: "UPDATE_CART_LOADING",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_ERROR: "UPDATE_CART_ERROR",
  DELETE_CART_LOADING: "DELETE_CART_LOADING",
  DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",
  DELETE_CART_ERROR: "DELETE_CART_ERROR",
  CLEAR_OLD_DATA: "CLEAR_OLD_DATA",
};
export { TYPES };
