const TYPES = {
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_LOADING: "GET_CART_LOADING",
  GET_CART_ERROR: "GET_CART_ERROR",
};
export { TYPES };
