const TYPES = {
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_LOADING: "GET_ORDERS_LOADING",
  GET_ORDERS_ERROR: "GET_ORDERS_ERROR",
  GET_INFORMATION_SUCCESS: "GET_INFORMATION_SUCCESS",
  GET_INFORMATION_LOADING: "GET_INFORMATION_LOADING",
  GET_INFORMATION_ERROR: "GET_INFORMATION_ERROR",
  UPDATE_INFORMATION_SUCCESS: "UPDATE_INFORMATION_SUCCESS",
  UPDATE_INFORMATION_LOADING: "UPDATE_INFORMATION_LOADING",
  UPDATE_INFORMATION_ERROR: "UPDATE_INFORMATION_ERROR",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
  GET_DETAIL_ORDER_SUCCESS: "GET_DETAIL_ORDER_SUCCESS",
  GET_DETAIL_ORDER_LOADING: "GET_DETAIL_ORDER_LOADING",
  GET_DETAIL_ORDER_ERROR: "GET_DETAIL_ORDER_ERROR",
};
export { TYPES };
