const TYPES = {
  GET_DETAIL_ORDER_SUCCESS: "GET_DETAIL_ORDER_SUCCESS",
  GET_DETAIL_ORDER_LOADING: "GET_DETAIL_ORDER_LOADING",
  GET_DETAIL_ORDER_ERROR: "GET_DETAIL_ORDER_ERROR",
};
export { TYPES };
